import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Footer from './components/footer'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Book Diary',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className={`antialiased m-2 p-4 h-full flex flex-col lg:justify-center lg:items-center`}>
        <div className='flex flex-col lg:min-h-60dvh lg:shadow-lg lg:p-8 lg:min-w-screen-sm lg:max-w-screen-md'>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
