import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { caveat } from '@/app/ui/fonts'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Book Diary',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={`${geistSans.variable} ${geistMono.variable} bg-gradient-to-b from-white to-slate-200`}>
      <body className={`antialiased m-4 p-4 h-100dvh`}>{children}</body>
    </html>
  )
}
